### ISSUE TITLE
How to Update macOS - Or Safely Delete This Installation

### ISSUE THREAD

**Issue by iBanJavascript** [chris1111/Geforce-Kepler-patcher#12]
Hi chris1111 - 
First, thx for your helpful projects & tips.

I have a hackintosh with a GeForce GT710 2MB dGPU. It was running Big Sur fine, but when Monterey 12.0.1 was released and dropped support for Kepler, I found your patcher.

I followed your directions closely & the install worked. I've had no issues since then and have been running 12.0.1 fine, other than my machine won't boot at all if I change "_SecureBootModel_" to anything besides "_Disabled_" in my OpenCore 0.7.5 _config.plist_.

My question is: With the OpenCore settings your patcher requires, **how can I update now to 12.1**, or future updates?

If I can't update the OS, _please tell me how I can safely UNINSTALL all the kexts & elements that your Geforce-Kepler-patcher installed_.

**UPDATE**: I went the gibMacOS route to install 12.1. It was successful, although it deleted all the extensions your patcher installed. Meaning when I booted up in 12.1, I didn't have QE/QI. So I re-applied your patcher to my new 12.1 install and it worked. In short, a bit of a hassle, but fortunately the patch is still valid.

You MIGHT want to consider addressing the upgrade to 12.1 for users of this patch.

**Comment by testhmf33** [comment]
thank you for your patch CHRISS 
works fine with beta 12.2 !!!!!!
CLOVER 5142 and OPEN CORE 0.7.7 💥👍
@iBanJavascript : if you don't have 15 secondes to apply this patch ,change your graphic card !!!!
![Capture d’écran 2021-12-17 à 08 31 02](https://user-images.githubusercontent.com/91620557/146507326-c89ce767-7130-49c9-8d1a-d30e383fe836.png)
![Capture d’écran 2021-12-17 à 09 01 25](https://user-images.githubusercontent.com/91620557/146511091-946bac96-fdaa-468a-a20a-0054a8bb5a40.png)
![Capture d’écran 2021-12-17 à 09 57 34](https://user-images.githubusercontent.com/91620557/146518337-fa54b6fe-c622-4c42-ae9c-a97894f12d57.jpg)

**Comment by adaml75** [comment]
Thank you for the patch Chris! Can we enable SIP just to update? I read somwhere that people did this (just switched it on that the update shows).

**Comment by chris1111** [comment]
> Thank you for the patch Chris! Can we enable SIP just to update? I read somwhere that people did this (just switched it on that the update shows).

@adaml75 
I dont have issue Update with SIP disable, I just did that Update latest Beta 2
@testhmf33  Yes Thanks 😇
![Screen Shot 2021-12-17 at 10 24 41 AM](https://user-images.githubusercontent.com/6248794/146567549-ad5a2970-f0b3-4c4d-aace-a79fe001e6e3.png)

**Comment by starlifezzz** [comment]
> > 谢谢你的补丁克里斯！我们可以启用SIP只是为了更新吗？我在某处读到人们这样做了（只是在更新显示的情况下打开它）。
> 
> @adaml75 我没有问题 禁用 SIP 更新，我只是做了更新最新的 Beta 2 @testhmf33 是的，谢谢😇 ![屏幕截图 2021-12-17 at 10 24 41 AM](https://user-images.githubusercontent.com/6248794/146567549-ad5a2970-f0b3-4c4d-aace-a79fe001e6e3.png)

Hello, developer, I want to update macos, and I can’t boot after enabling the sip setting. What should I do?

> > Thank you for the patch Chris! Can we enable SIP just to update? I read somwhere that people did this (just switched it on that the update shows).
> 
> @adaml75 I dont have issue Update with SIP disable, I just did that Update latest Beta 2 @testhmf33 Yes Thanks 😇 ![Screen Shot 2021-12-17 at 10 24 41 AM](https://user-images.githubusercontent.com/6248794/146567549-ad5a2970-f0b3-4c4d-aace-a79fe001e6e3.png)

Hello, developer, I want to update macos, and I can’t boot after enabling the sip setting. What should I do?

**Comment by techs2resolve** [comment]
I am not able patch it on my Gigabyte 560 DS3H MOTHERBOARD. Can anyone help me to run monterey 12.1 i am using below config.

Gigabyte 560 DS3H MOTHERBOARD
Gigabyte Nvidia GT 730 DDR3
CORE I5 11TH GEN ROCKET LAKE.

**Comment by cagnulein** [comment]
@techs2resolve follow this https://github.com/chris1111/Geforce-Kepler-patcher/issues/11

**Comment by adaml75** [comment]
What settings do I need to apply see the update? Should I enable SIP? Some people apparently have it enabled.

**Comment by cagnulein** [comment]
@adaml75 follow this https://github.com/chris1111/Geforce-Kepler-patcher/issues/11#issuecomment-976774138 
I didn't touch SIP

**Comment by iBanJavascript** [comment]
I use OpenCore, so the Clover successes posted above don't necessarily apply to my case. 

Just wondering if your csr-active-config setting in config.plist is what chris1111 recommended (EF0F0000), or did you use a different bitmap? I used EF0F0000 but the OTA update never showed in System Preferences>Software Update. That's why I had to go the gibMacOS route to get the update. Again, this is with OpenCore, not Clover.

**Comment by starlifezzz** [comment]
I  find   reason  

1.  In OpenCore Install Guide    
### OTA Updates
Starting with Monterey, updates are not delivered to T2 Macs which don't have Secure Boot enabled, and updates do not install properly if your SecureBootModel does not match your machine (ie. non-T2 SMBIOS using j137 or iMacPro1,1 using j160). Hackintoshes which use a T2 SMBIOS MUST have OpenCore 0.7.4+ with SecureBootModel set to Default. If your SMBIOS does not have a T2 chip, then either Default or Disabled is ok. More information is available on the Apple Secure Boot page (opens new window).
2. why not hava ota to me ?
   because  Geforce-Kepler-patcher need  
   SecureBootModel ➤ Disabled

but   if  you    smbios   is    mac  pro  or  

<p class="custom-block-title" style="scroll-behavior: smooth; line-height: 1.7; font-weight: 600; letter-spacing: 0.1rem; margin-bottom: -0.4rem; color: rgb(44, 62, 80); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">T2 SMBIOS List</p>

SMBIOS | Minimum macOS Version
-- | --
iMacPro1,1 (December 2017) | 10.13.2 (17C2111)
MacBookPro15,1 (July 2018) | 10.13.6 (17G2112)
MacBookPro15,2 (July 2018) | 10.13.6 (17G2112)
Macmini8,1 (October 2018) | 10.14 (18A2063)
MacBookAir8,1 (October 2018) | 10.14.1 (18B2084)
MacBookPro15,3 (May 2019) | 10.14.5 (18F132)
MacBookPro15,4 (July 2019) | 10.14.5 (18F2058)
MacBookAir8,2 (July 2019) | 10.14.5 (18F2058)
MacBookPro16,1 (November 2019) | 10.15.1 (19B2093)
MacPro7,1 (December 2019) | 10.15.1 (19B88)
MacBookAir9,1 (March 2020) | 10.15.3 (19D2064)
MacBookPro16,2 (May 2020) | 10.15.4 (19E2269)
MacBookPro16,3 (May 2020) | 10.15.4 (19E2265)
MacBookPro16,4 (June 2020) | 10.15.5 (19F96)
iMac20,1 (August 2020) | 10.15.6 (19G2005)
iMac20,2 (August 2020) | 10.15.6 (19G2005)



above  smbios  list  with    Geforce-Kepler-patcher   have  conflict
i  change to   imac  19.2  , already to 12.1 OTA
