### ISSUE TITLE
Xcode 13.3 and newer Simulator issue 

### ISSUE THREAD

**Issue by Prince014** [chris1111/Geforce-Kepler-patcher#29]
Hey,
No doubt this tool work so well,
But one issue i have noticed that after using this patch tool Xcode 13.3  and Xcode 13.3.1 simulator's stoped working, simulator not even load, although there is no issue with Android simulators and Xcode 13.0 or lower simulators.
Dont know what is wrong hoping you can guide on this.
Thanks

**Comment by macenjoyer** [comment]
Can confirm, Simulator and SwiftUI Previews don't work

![image](https://user-images.githubusercontent.com/103370823/164894934-96ea40db-d363-40e8-9699-14a9c05d803b.png)

**Comment by Prince014** [comment]
Why this patcher working for xcode 13.0, and not for 13.3

Have you got any solution?
Or can you suggest something

**Comment by skiezest** [comment]
No idea why this happens, let's hope Chris figures it out

**Comment by Prince014** [comment]
I have seen his reply on a glitch related to visual studio.
He said don't expect too much

**Comment by vinukn335** [comment]
Anyone got any error log? I could not find any logs.

**Comment by Prince014** [comment]
No error

**Comment by chris1111** [comment]
No issue here latest Monterey Beta / Xcode 13.2.1

**Comment by chris1111** [comment]
No issue here latest Monterey Beta / Xcode 13.2.1
![Screen Shot 2022-04-27 at 6 11 03 PM](https://user-images.githubusercontent.com/6248794/165639962-2c2683e3-3182-4f79-ba71-8ccdbf960a66.png)

**Comment by Prince014** [comment]
Hey chris issue is from xcode 13.3 and newer version, 
Please try xcode 13.3 once 
I have have tested xcode 13.3 on monteret 12.0.1 to 12.3 
It is not working 
Below version of xcode is working fine please guide if i am Missing something

**Comment by macenjoyer** [comment]
Try on Xcode 13.3 

Afaik you're using Clover so it might work on Clover but not OpenCore

**Comment by Prince014** [comment]
i dont think it has anything to do with clover or open core because. i had tried without patching (on low graphics) simulator was working but after patching simulator stopped working

**Comment by vinukn335** [comment]
This patch is working with 12.4 beta, but xcode simulator not working.

**Comment by Prince014** [comment]
That is the actual issue xcode 13.3

**Comment by vinukn335** [comment]
Anyone tried xcode 13.3 with old simulator?

**Comment by testhmf33** [comment]
![Capture d’écran 2022-04-30 à 10 24 06](https://user-images.githubusercontent.com/91620557/166098144-1a55c0d2-c12e-4da3-a8be-44c72c9edcf7.png)

**Comment by Prince014** [comment]
Bro please try xcode 13.3

**Comment by testhmf33** [comment]
![Capture d’écran 2022-04-30 à 10 52 13](https://user-images.githubusercontent.com/91620557/166098899-b1b9e909-c867-4cc2-8da1-b73ab2605d33.png)

**Comment by Prince014** [comment]
Bro test xcode13.3 on gt710 graphics card after using chrish kepler patcher...

On inbuilt graphics everything is working fine, even on haswell processor

**Comment by testhmf33** [comment]
don't work with Xcode 13.3 and Gt 710
change your Graphic card !!!!!
that's all

**Comment by chris1111** [comment]
> don't work with Xcode 13.3 and Gt 710 change your Graphic card !!!!! that's all

Closed issue

**Comment by The3DWizard** [comment]
Same issue here for me with opencore legacy patcher running on macbook pro late 2013 with NVidia Geforce 750 GT. All simulators above iOS 15.2 (15.2 is the latest release that is still working) fail for me (i.e. only show black screen). So starting from XCode 13.3, the default simulator is higher than 15.2, so issue arises. Have not seen a fix for this anywhere. For me the biggest issue is that this also affects Playgrounds, because those rely on iOS simulator as well.

**Comment by VicoErv** [comment]
Hello, I have solution for you guys who using cpu that have igpu.
for example my cpu is intel core i3-10105 with igpu intel uhd 630.

the steps you need to take is:
1. patch ur igpu framebuffer, thanks to [dortania](https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/) tutorial. but you need to search the device-id that have connectors above zero, if you have zero connectors then the gpu work headlessly, so simulator wouldn't render.
2. reboot your system
3. open simulator and check prefer igpu.

![Screen Shot 2022-08-21 at 18 15 09](https://user-images.githubusercontent.com/26959883/185788369-b296a3f8-aa3d-4e57-96ec-03798e7fad27.png)
![Screen Shot 2022-08-21 at 18 13 32](https://user-images.githubusercontent.com/26959883/185788351-c1f37f7e-4266-471d-8047-617f427c80d0.png)

**Comment by The3DWizard** [comment]
@VicoErv Does this work when using an external display? Also, do live preview and playgrounds work this way, too?

**Comment by VicoErv** [comment]
> @VicoErv Does this work when using an external display? Also, do live preview and playgrounds work this way, too?

I'm using external display

**Comment by The3DWizard** [comment]
@VicoErv : Thank you so much. I finally got around to try out your solution and it is working for me on my Macbook Pro 15" late 2013 model with dedicated Kepler GPU.

To everyone interested in my exact approach I will give a short step by step for my specific case, but essentially it is all explained in the [dortania](https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/) tutorial that VicoErv mentioned before. So here we go:

Opening System Information I get the necessary system information about my macbook:
![image](https://user-images.githubusercontent.com/8538860/187031115-0fdc9b40-44c5-4a2b-aacd-845fec333a06.png)

Going to [everymac](https://everymac.com/ultimate-mac-lookup/) I can lookup the exact processor name for my model, which turns out to be I7-4850HQ .

With this information I go to [intel ark](https://ark.intel.com/content/www/us/en/ark/products/76086/intel-core-i74850hq-processor-6m-cache-up-to-3-50-ghz.html), which gives me my device id for my IGPU, which in my case is  0xD26 .

With this information I go to [WhateverGreen's list](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md), which tells me that I have an Intel HD 5200 IGPU and my device is natively support by macOS. This means that the only thing I need to modify in config.plist is the framebuffer personality, i.e. I need to set an entry for "AAPL,ig-platform-id". No need to set "device-id" in my case. I took the first recommend framebuffer from WhateverGreen's list, which for me is 0x0A260005 (laptop, HD 5200).

In Little Endian format (which is needed for config.plist) the framebuffer id is 0500260A. So the last step is to put this entry in my config.plist on my EFI partition. So find disk identifier via terminal command "diskutil list", then mount this disk via "sudo diskutil mount diskidentifier". The final step is to modify my config.plist like this:
![Dictionary](https://user-images.githubusercontent.com/8538860/187031821-f8cabea5-2591-405f-8a30-83b069efefcd.png)

That is it.

Now I can use Simulators for iOS and iPadOS with version 16.0. In addition to that Playgrounds and Live Preview is also working now. This was tested by me on macOS 12.5.1 with XCode 14 Beta 6 on IOS 16 simulator. Have not tried out other other iOS versions in simulator, but they should work fine now. Once again thanks to VicoErv for the information and of course all the people working on the opencore project.

**Comment by chris1111** [comment]
@The3DWizard
 Why using a patch with dedicated Kepler GPU if you have 2013 MacBook with Intel Iris support in Monterey 12

**Comment by The3DWizard** [comment]
@chris1111 Honestly at first I just followed the process of opencore legacy patcher and thought everything was working fine when applying the Kepler patch until I found out that XCode Simulators had issues with that. Then I though I needed the dedicated GPU for using an external display.
I guess what you mean is why I did not deactivate the Kepler GPU completely and just use the internal one, right? I guess it is just due to a lack of knowledge on my part. Until recently I didn't even know that the integrated Intel GPU was still officially supported, had no issues with the simulators and was also able to run the external display while the dedicated GPU is "deactivated".
